spring:
  main:
    allow-bean-definition-overriding: true
#Configuration
server:
  servlet:
    context-path: /motivation
---
#JPA PROPERTIES
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
    ddl-auto: create
    #create-drop
---
#DATABASE
spring:
  datasource:
    platform: postgres
    #   For Docker
    #    url: jdbc:postgresql://localhost:5432/motivation
    #    For Local host
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
  database:
    driverClassName: org.postgresql.Driver
---
#Log4j

logging:
  file:
    name: src/main/resources/logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.howtodoinjava: trace
    org.hibernate: ERROR

---
# Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
spring:
  http:
    encoding:
      charset: UTF-8
      # Enable http encoding support.
      enabled: true
      # Force the encoding to the configured charset on HTTP requests and responses.
      force: true
---
#email configuration

spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: b2592fe3eaad13
    password: 0bf2ccb8316813

server:
  port: 8080
