spring:
  main:
    allow-bean-definition-overriding: true
#Configuration
server:
  servlet:
    context-path: /motivation
---
#JPA PROPERTIES
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
#spring:
#jpa:
#database: H2
#show-sql: true
#hibernate:
    #ddl-auto: validate
    #create-drop
---
#DATABASE
#spring:
#datasource:
#platform: h2
    #   For Docker
    #    url: jdbc:postgresql://localhost:5432/motivation
    #    For Local host
    #url: jdbc:h2:tcp://localhost:9092/mem:motivation
    #user: sa
    #password:
    #driverClassName: org.postgresql.Driver
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    #hibernate.dialect: org.hibernate.dialect.PostgreSQL14Dialect.
#url: jdbc:h2:tcp://localhost:9092/mem:motivation
#user: sa
#password:
    #jpa:
    #show-sql: true
      #hibernate:
    #ddl-auto: update
    #database: H2
    #database:
    #driverClassName: org.h2.Driver
---
#Log4j

logging:
  file:
    name: src/main/resources/logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.howtodoinjava: trace
    org.hibernate: ERROR

---
# Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
spring:
  http:
    encoding:
      charset: UTF-8
      # Enable http encoding support.
      enabled: true
      # Force the encoding to the configured charset on HTTP requests and responses.
      force: true
---
#email configuration

spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: b2592fe3eaad13
    password: 0bf2ccb8316813

server:
  port: 8080
